version: '3.5'

services:
  strategiestemplates.api:
    environment:
      - EventBusConnection=${PROD_SERVICE_BUS_CONNECTION}
      - EventBusUserName=${TRADING_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TRADING_SERVICE_BUS_PASSWORD}     
      - EventBusRetryCount=5
      - SubscriptionClientName=StrategiesTemplates
      - LogLevelDefault=Warning
      - SeqConnection=${PROD_SERVICE_SEQ_CONNECTION}
    ports:
      - "5019:80"