version: '3.5'

services:
  tradesstorage.api:
    environment:
      - EventBusConnection=${PROD_SERVICE_BUS_CONNECTION}
      - EventBusUserName=${TRADING_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TRADING_SERVICE_BUS_PASSWORD}     
      - EventBusRetryCount=5
      - SubscriptionClientName=TradesStorage
      - LogLevelDefault=Warning
      - SeqConnection=${PROD_SERVICE_SEQ_CONNECTION}
      - DatabaseDir=/Databases
    ports:
      - "5000:80"   
    volumes:
      - /Trading/Databases:/Databases