version: '3.5'

services:
   tradesreader:
    environment:
      - EventBusConnection=${PROD_SERVICE_BUS_CONNECTION}
      - EventBusUserName=${TRADING_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TRADING_SERVICE_BUS_PASSWORD}     
      - EventBusRetryCount=5
      - UseResilientHttp=False
      - SubscriptionClientName=TradesReaderBinance
      - SeqConnection=${PROD_SERVICE_SEQ_CONNECTION}
      - ExchangeName=BINANCE
      - Proxy=
      - RequestTimeoutSecond=30
      - LogLevelDefault=Warning
      - Urls__TradeCoordinator=http://${PROD_TRADE_COORDINATOR_SERVICE}
      - Urls__TradeStorage=http://${PROD_TRADE_STORAGE_SERVICE}
      - Urls__Markets=http://${PROD_MARKETS_SERVICE}
      - Urls__Identity=http://${PROD_IDENTITY_SERVICE}
    ports:
      - "5006:80"

