version: '3.5'

services:
  markets.websocket.api:
    environment:
      - EventBusConnection=${PROD_SERVICE_BUS_CONNECTION}
      - EventBusUserName=${TRADING_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TRADING_SERVICE_BUS_PASSWORD}     
      - EventBusRetryCount=5
      - SubscriptionClientName=MarketsWebSocket
      - LogLevelDefault=Warning
      - RequestTimeoutSecond=20
      - SeqConnection=${PROD_SERVICE_SEQ_CONNECTION}
      - SleepStartInMilliseconds=1000
      - UseToken=False
      - BinanceUrl=https://api1.binance.com
      - BinanceFutureUrl=https://fapi.binance.com
    ports:
      - "5034:80"